### ISSUE TITLE
Add a license to the repository

### ISSUE THREAD

**Issue by txtsd** [CallMeBruce/nightwalker#6]
Please add a license to the repository

**Comment by CallMeBruce** [comment]
@txtsd , for myself, I would be inclined to apply an MIT license. I see you have enquired on the original repo also https://github.com/repslet/nightwalker/issues/21#issue-2631407134 . I'm not really sure of the correct approach when there is no license on that, is it not presumptuous to license this derivative first?

**Comment by txtsd** [comment]
@CallMeBruce Since upstream is archived, no changes can be expected, in which case it is okay to go ahead and license it as you see fit.

**Comment by CallMeBruce** [comment]
@txtsd ok, thanks.
